name: process_rosbag
channels:
  - defaults
dependencies:
  - python=3.8.10
  - pip
  - pip:
    - rospkg
    - gnupg
    - pycryptodomex
    - opencv-python
    - tqdm
    - pyyaml
    - python-gnupg
    - pillow